name: Update package (new)
description: Report an outdated package
title: "package: old -> new"
labels: [update]
body:
  - type: markdown
    attributes:
      value: |
        <div align="center">
          <img src="https://github.com/glfs-book/slfs/blob/trunk/images/slfs-logo.svg?raw=true" width="10%">
          <h1>SLFS</h1>
        </dev>

        ### Update package

  - type: dropdown
    id: semver
    attributes:
      label: Semantic version bump
      description: How big is the version bump in this update?
      options:
        - Major
        - Minor
        - Patch
        - Nano
        - Commit
        - Other
      default: 2
    validations:
      required: true

  - type: input
    id: release
    attributes:
      label: Release
      description: A link to the new release.
      placeholder: https://github.com/nushell/nushell/releases/tag/0.109.1
    validations:
      required: false

  - type: input
    id: changelog
    attributes:
      label: Changelog
      description: A link to the changelog.
      placeholder: https://www.nushell.sh/blog/2025-12-02-nushell_v0_109_1.html#changes-toc
    validations:
      required: false

  - type: dropdown
    id: security
    attributes:
      label: Security
      description: Does this release fix a security vulnerability?
      options:
        - 'yes'
        - 'no'
      default: 1
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: Extra information
      description: Anything else we should know.
    validations:
      required: false
