#!/bin/bash

# Helper script for checking files in docstubgen.
# (C) Seal Sealy 2025

# JARs are actually internally ZIP archives... sigh

if [ "${1##*.}" = "jar" ]; then
	file $1 | grep -E "Zip" > /dev/null 2>&1
	if [ $? -eq 0 ]; then
		exit 0
	fi
fi 

# ELF is binaries and shared libraries
# scripts is all kinds of misc .sh stuff and more
# ar archive is for static libs
# DLL is Windows DLLs

file $1 | grep -E "ELF|script|ar archive|DLL" > /dev/null 2>&1
if [ $? -ne 0 ]; then
	exit 1
fi
exit 0
