#!/usr/bin/python3

# Quick doc stub generator script.
# Warning: doesn't do *all* the work for you.
# Review output manually after the script finishes.
# (C) Seal Sealy, 2025

import os
import sys
import shutil
import itertools

# INTERNAL FLAGS, DO NOT TOUCH
nobinflag = False
nolibflag = False

# These flags can be modified by environment variables.
# If you don't want to add some EXPORTs to your shell rc file for some reason, feel
# free to change these to your liking. Just don't commit these changes.
libdocflag = False
recsearchflag = False
nowarnflag = False
checkbinflag = False
trustedinputflag = False

# Use this flag only as a last resort. It disables any and all user input sanitization
# happening during binary checking. If you enable this and you try to document some
# sketchy package, you have just thrown out your last line of defense. There's a reason
# this is undocumented.
idontcareaboutsecurity = False

def checklib(i, f):
	return not (libdocflag and (".a" in os.path.basename(os.path.join(i, 
		f)) or ".so" in os.path.basename(os.path.join(i, f))))

def callcheckfile(path):
	if not idontcareaboutsecurity:
		dangerouschars = dict.fromkeys(map(ord, "&'\"\\|><"), None)
		path2 = path.translate(dangerouschars)
		if path != path2:
			print('Warning: possible ACE attempt detected. CHECK SYSTEM FOR \
HACKER PRESENCE NOW.')
			sys.exit(1)
	if os.waitstatus_to_exitcode(os.system(f'{checkfilepath} {os.path.abspath(path)}')) == 0:
		return 0
	else:
		return 1


if len(sys.argv) < 3:
	print(f"Usage: {sys.argv[0]} pkgname folder1 <folder2> <folder3> ...", file=sys.stderr)
	print('Environment variable descriptions have been moved to docstubgen(1).', file=sys.stderr)
	sys.exit(1)

if os.getenv('DOCSTUBGEN_DOCUMENT_LIBRARIES'):
	libdocflag = True

if os.getenv('DOCSTUBGEN_RECURSIVE_SEARCH'):
	recsearchflag = True

if os.getenv('DOCSTUBGEN_I_KNOW_WHAT_I_AM_DOING'):
	nowarnflag = True

if os.getenv('DOCSTUBGEN_BINARY_DETECT'):
	if (not os.getenv('DOCSTUBGEN_TRUSTED_INPUT')) and (not trustedinputflag):
		print('SECURITY WARNING!!! DO NOT DISREGARD', file=sys.stderr)
		print('You have set the DOCSTUBGEN_BINARY_DETECT environment variable.', file=sys.stderr)
		print('This variable enables attempted automatic detection of binaries \
and scripts using the file command, which involves passing user input into executed commands.', file=sys.stderr)
		print('While the LFS-QOL editors have tried to sanitize user input from any unwanted \
characters which may lead to ACE, there are simply too many ways to cause ACE in this scenario.', file=sys.stderr)
		print('If you try to generate documentation for some sketchy application and it \
leads to your computer getting hacked by some state-sponsored hackers, we disclaim ANY \
responsibility for such an act and for any damages caused.', file=sys.stderr)
		print('If you have read this fully and have considered the risks, set the \
DOCSTUBGEN_TRUSTED_INPUT environment variable. You have been warned.', file=sys.stderr)
		sys.exit(1)
	if os.path.exists("/usr/libexec/checkfile.sh"):
		checkfilepath = "/usr/libexec/checkfile.sh"
	elif shutil.which("checkfile.sh") is None:
		print('Error: checkfile.sh helper script not found in /usr/libexec or $PATH.', file=sys.stderr)
		sys.exit(1)
	else:
		checkfilepath = shutil.which("checkfile.sh")
	checkbinflag = True

folderlist = []
for d in range(len(sys.argv)):
	if d == 0 or d == 1:
		continue
	if recsearchflag:
		for tmp in [x[0] for x in os.walk(sys.argv[d])]:
			folderlist.append(tmp)
	else:
		folderlist.append(sys.argv[d])

# sublist structure
# [<symlink name>, 's', <symlink target>]
# OR
# [<file name>, 'f', 'FILLER']

filelist = []
for d in folderlist:
	i = d
	if not os.path.isdir(i):
		print(f"Error: nonexistent folder {i}", file=sys.stderr)
		sys.exit(1)
	for f in os.listdir(i):
		if os.path.islink(os.path.join(i, f)):
			if os.path.isfile(os.path.normpath(os.path.join(os.path.dirname(os.path.join(i, \
					f)), os.readlink(os.path.join(i, f))))):
				if libdocflag:
					if checklib(i, f) and callcheckfile(os.path.normpath(os.path.join(os.path.dirname(os.path.join(i, \
							f)), os.readlink(os.path.join(i, f))))) == 0:
						filelist.append([f, 's', os.path.basename(os.readlink( \
							os.path.join(i, f)))])
				else:
					if callcheckfile(os.path.normpath(os.path.join(os.path.dirname(os.path.join(i, \
							f)), os.readlink(os.path.join(i, f))))) == 0:
						filelist.append([f, 's', os.path.basename(os.readlink(os.path.join(i, \
								f)))])
		elif os.path.isfile(os.path.join(i, f)):
			if libdocflag:
				if checklib(i, f) and callcheckfile(os.path.join(i, f)) == 0:
					filelist.append([f, 'f', 'FILLER'])
			else:
				if callcheckfile(os.path.join(i, f)) == 0:
					filelist.append([f, 'f', 'FILLER'])

filelist.sort()
filelist = list(filelist for filelist,_ in itertools.groupby(filelist))
filelist = sorted(filelist, key=lambda e: e[0])

if libdocflag:
	liblist = []
	for d in folderlist:
		i = d
		if not os.path.isdir(i):
			print(f"Error: nonexistent folder {i}", file=sys.stderr)
			sys.exit(1)
		for f in os.listdir(i):
			if os.path.islink(os.path.join(i, f)):
				if os.path.isfile(os.path.normpath(os.path.join(os.path.dirname(os.path.join(i, \
						f)), os.readlink(os.path.join(i, f))))):
					continue
			elif os.path.isfile(os.path.join(i, f)) and '.a' in os.path.basename(os.path.join(i, f)) and callcheckfile(os.path.join(i, f)) == 0:
				liblist.append([f, 'f', 'FILLER'])
			elif os.path.isfile(os.path.join(i, f)) and '.so' in os.path.basename(os.path.join(i, f)) and callcheckfile(os.path.join(i, f)) == 0:
				tmplst = f.split('.')
				tmp = tmplst[0]
				for h in tmplst[1:]:
					# isdigit only works for positive integers and doesn't work with floats
					# but it should do, shared object naming doesn't involve floats or
					# negative integers
					if not h.isdigit():
						tmp = tmp + '.' + h
				liblist.append([tmp, 'f', 'FILLER'])

	liblist.sort()
	liblist = list(liblist for liblist,_ in itertools.groupby(liblist))
	liblist = sorted(liblist, key=lambda e: e[0])

print('''  <sect2 role="content">
    <title>Contents</title>

    <segmentedlist>
      <segtitle>Installed Programs</segtitle>
      <segtitle>Installed Libraries</segtitle>
      <segtitle>Installed Directories</segtitle>

      <seglistitem>
        <seg>''')
tmp = '          '
for i in filelist:
	if i[1] == 'f':
		tmp2 = tmp + i[0] + ', '
	elif i[1] == 's':
		tmp2 = tmp + i[0] + f' (link to {i[2]})' + ', ' 
	#print(tmp2)
	if len(tmp2) <= 80:
		tmp = tmp2
	else:
		print(tmp)
		tmp3 = tmp2.split(', ')
		tmp = '          ' + tmp3[-2] + ', '
		tmp2 = ', '.join(tmp3[:-2])
if len(filelist) == 0:
	if not nowarnflag:
		print('Warning: no acceptable binaries found.', file=sys.stderr)
		print('Did you forget to set DOCSTUBGEN_RECURSIVE_SEARCH?', file=sys.stderr)
		print('Putting "None" into XML.', file=sys.stderr)
	print('          None', end='')
	nobinflag = True
# this is a HACK to avoid generating incorrect binary lists in corner cases
# where we already got through the entire filelist array, already printed out tmp2,
# but there's still one binary left in tmp
elif tmp.count(', ') == 1:
	print(tmp, end='')
else:
	print(tmp2, end='')
print('''
        </seg>
        <seg>''')
if not libdocflag:
	print('          TODO')
else:
	tmp = '          '
	for i in liblist:
		tmp2 = tmp + i[0] + ', '
		#print(tmp2)
		if len(tmp2) <= 80:
			tmp = tmp2
		else:
			print(tmp)
			tmp3 = tmp2.split(', ')
			tmp = '          ' + tmp3[-2] + ', '
			tmp2 = ', '.join(tmp3[:-2])
	if len(liblist) == 0:
		if not nowarnflag:
			print('Warning: no acceptable libraries found.', file=sys.stderr)
			print('Did you forget to set DOCSTUBGEN_RECURSIVE_SEARCH or did you \
set DOCSTUBGEN_DOCUMENT_LIBRARIES by mistake?', file=sys.stderr)
			print('Putting "None" into XML.', file=sys.stderr)
		print('          None', end='')
		nolibflag = True
	# this is a HACK to avoid generating incorrect library lists in corner cases
	# where we already got through the entire liblist array, already printed out
	# tmp2, but there's still one library left in tmp
	elif tmp.count(', ') == 1:
		print(tmp, end='')
	else:
		print(tmp2, end='')
	print()
print('''        </seg>
        <seg>
          TODO
        </seg>
      </seglistitem>
    </segmentedlist>
''', end='')

if nobinflag:
	if libdocflag:
		if nolibflag:
			print('''
  </sect2>
''')
			sys.exit(0)
	else:
		print('''
  </sect2>
''')
		sys.exit(0)

print('''
    <variablelist>
      <bridgehead renderas="sect3">Short Descriptions</bridgehead>
      <?dbfo list-presentation="list"?>
      <?dbhtml list-presentation="table"?>
''', end='')

for g in filelist:
	if g[1] == 'f':
		i = g[0]
		print(f'''
      <varlistentry id="{i}">
        <term><command>{i}</command></term>
        <listitem>
          <para>
            TODO
          </para>
          <indexterm zone="{sys.argv[1]} {i}">
            <primary sortas="b-{i}">{i}</primary>
          </indexterm>
        </listitem>
      </varlistentry>
''', end='')
	elif g[1] == 's':
		i = g[0]
		l = g[2]
		print(f'''
      <varlistentry id="{i}">
        <term><command>{i}</command></term>
        <listitem>
          <para>
            is a symlink pointing to <command>{l}</command>
          </para>
          <indexterm zone="{sys.argv[1]} {i}">
            <primary sortas="b-{i}">{i}</primary>
          </indexterm>
        </listitem>
      </varlistentry>
''', end='')

if libdocflag:
	for g in liblist:
		i = g[0]
		# yes this is a hack
		# but i can't figure out how rsplit works, I'm tired and it's 11:49PM
		if '.a' in i:
			f = i[:-2]
		elif '.so' in i:
			f = i[:-3]
		else:
			f = i
		print(f'''
      <varlistentry id="{f}">
        <term><filename class="libraryfile">{i}</filename></term>
        <listitem>
          <para>
            TODO
          </para>
          <indexterm zone="{sys.argv[1]} {f}">
            <primary sortas="c-{f}">{i}</primary>
          </indexterm>
        </listitem>
      </varlistentry>
''', end='')

print('''
    </variablelist>

  </sect2>
''')
